// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA7oLrwMIxzN8jdHl2AICAyRhKXNFG9lM',
    appId: '1:205496890981:web:67e9730ab316d105c9788c',
    messagingSenderId: '205496890981',
    projectId: 'emergency-scanner-caa09',
    authDomain: 'emergency-scanner-caa09.firebaseapp.com',
    storageBucket: 'emergency-scanner-caa09.firebasestorage.app',
    measurementId: 'G-WX4FS2QB3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJHcXhQi5jAN9gghprNFCiCHqGMDahw8g',
    appId: '1:205496890981:android:eaf6531389af1c29c9788c',
    messagingSenderId: '205496890981',
    projectId: 'emergency-scanner-caa09',
    storageBucket: 'emergency-scanner-caa09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSaZVxzzY_Ql4uvAkA0yGBcyGmX3uuN2s',
    appId: '1:205496890981:ios:f6104fcd7b7a9578c9788c',
    messagingSenderId: '205496890981',
    projectId: 'emergency-scanner-caa09',
    storageBucket: 'emergency-scanner-caa09.firebasestorage.app',
    iosBundleId: 'com.emergencyalert.emergencyAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSaZVxzzY_Ql4uvAkA0yGBcyGmX3uuN2s',
    appId: '1:205496890981:ios:f6104fcd7b7a9578c9788c',
    messagingSenderId: '205496890981',
    projectId: 'emergency-scanner-caa09',
    storageBucket: 'emergency-scanner-caa09.firebasestorage.app',
    iosBundleId: 'com.emergencyalert.emergencyAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA7oLrwMIxzN8jdHl2AICAyRhKXNFG9lM',
    appId: '1:205496890981:web:7b397bb14c4b98eec9788c',
    messagingSenderId: '205496890981',
    projectId: 'emergency-scanner-caa09',
    authDomain: 'emergency-scanner-caa09.firebaseapp.com',
    storageBucket: 'emergency-scanner-caa09.firebasestorage.app',
    measurementId: 'G-MWF1NBKLDF',
  );
}
